Repository Ericgacoki/sudofy, pull requests merged in 2021-03, with the labels that each got.

#4 Updated the read me file
  README.md
Labels: ready for final review

#5 Update README.md
  README.md
Labels: assigned for review, final review

#7 Workflow updates
  app/build.gradle
  app/src/main/java/com/ericg/sudofiemed/adapter/FirstAidsAdapter.kt
  app/src/main/java/com/ericg/sudofiemed/model/FirstAidData.kt
  app/src/main/java/com/ericg/sudofiemed/view/Details.kt
  app/src/main/java/com/ericg/sudofiemed/view/FirstAids.kt
  app/src/main/java/com/ericg/sudofiemed/view/ParentActivity.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_love.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/description_item.xml
  app/src/main/res/layout/fragment_details.xml
  app/src/main/res/navigation/app_navigation.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: ready for final review

#8 Code formatting
  app/src/main/java/com/ericg/sudofiemed/view/Details.kt
Labels: approved

#11 Cleaning the project-1
  app/src/main/java/com/ericg/sudofiemed/view/Details.kt
  app/src/main/java/com/ericg/sudofiemed/view/FirstAids.kt
  app/src/main/res/drawable/ic_loved.xml
  app/src/main/res/layout/description_item.xml
  app/src/main/res/layout/fragment_details.xml
Labels: final review
